uploads = []
generated = []

[[outputs]]
id = "n46QuysiOgq5AdJ9lgqzv"
uri = "file://artifacts/idalia-promo/public/audio/bg_music.mp3"
type = "audio"
title = "background music"

[[outputs]]
id = "vTc6EzgGucMZ4E3wB8__V"
uri = "file://artifacts/idalia-promo/public/audio/vo/biometry.mp3"
type = "audio"
title = "idalia_pt_biometry"

[[outputs]]
id = "t-yuEw-QN2_anvItYLIvq"
uri = "file://artifacts/idalia-promo/public/audio/vo/hook.mp3"
type = "audio"
title = "idalia_pt_hook"

[[outputs]]
id = "Vst0NZAA4EnR1pkHvKBiS"
uri = "file://artifacts/idalia-promo/public/audio/vo/dating.mp3"
type = "audio"
title = "idalia_pt_dating"

[[outputs]]
id = "dAhEfU1ZsPjJxM8ijhaPF"
uri = "file://artifacts/idalia-promo/public/audio/vo/records.mp3"
type = "audio"
title = "idalia_pt_records"

[[outputs]]
id = "ug-HKqpst63STKSW90i16"
uri = "file://artifacts/idalia-promo/public/audio/vo/outro.mp3"
type = "audio"
title = "idalia_pt_outro"

[[outputs]]
id = "Ghe78k9cNS-NTs1I5FNOd"
uri = "file://artifacts/idalia-promo/public/audio/vo/pricing.mp3"
type = "audio"
title = "idalia_pt_pricing"
