// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/doppler-redesign/Lean.tsx": () => import("../components/mockups/doppler-redesign/Lean.tsx"),
  "./components/mockups/doppler-redesign/Polished.tsx": () => import("../components/mockups/doppler-redesign/Polished.tsx"),
  "./components/mockups/doppler-redesign/Premium.tsx": () => import("../components/mockups/doppler-redesign/Premium.tsx")
};
